/*
  # Remove notification features that never actually ran

  Three pieces of the notification system were fully built but never wired
  to anything, which meant the admin UI promised functionality it didn't
  deliver:

  1. `check_view_milestones()` - defined to notify a seller when a product
     view count crosses a milestone, but nothing (no trigger, no edge
     function, no frontend call) ever invokes it.
  2. `process_scheduled_broadcasts()` - meant to send broadcasts an admin
     scheduled for later, but no cron job or function ever calls it, so a
     "scheduled" broadcast just sat forever with status='scheduled'. The
     "Agendar" option has been removed from the admin UI; broadcasts are
     now only ever sent immediately.
  3. `notification_templates` / `notification_rules` - a templates/rules
     engine editable from the admin Settings page, but the actual
     subscription-expiry notifications are generated by the
     check-expiring-subscriptions edge function with independently
     hardcoded text, completely disconnected from these tables. Editing a
     template here never changed what a real user received.

  This migration removes the dead function/table definitions to match the
  admin UI, which no longer exposes any of this. `notification_broadcasts`
  and `send_broadcast_notifications()` are untouched - manual "send now"
  broadcasts are real and still work.
*/

DROP FUNCTION IF EXISTS check_view_milestones(uuid, uuid);
DROP FUNCTION IF EXISTS process_scheduled_broadcasts();

DROP TABLE IF EXISTS notification_rules;
DROP TABLE IF EXISTS notification_templates;
